spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/iot_ascon
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 10000
jwt:
  iss: Momedu
  time-to-live: 3000
  secret-key: yakNF0lVMbT8lZlywv0OaJqEjKS0XLLk/xQvi7TYn6c=
momedu:
  rest-template:
    read-timeout: 180
    connection-timeout: 30



