server:
  port: 9494
  servlet:
    context-path: /api
  compression:
    enabled: true
  http2:
    enabled: true
spring:
  application:
    name: mom-edu-crm
  profiles:
    active: development
  jpa:
    database: default
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  flyway:
    baseline-on-migrate: true
